name: GitHub Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      run: |
          sudo apt-get update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git curl
          sudo apt-get install -y --no-install-recommends \
            python2.7 \
            python3.4 \
            python3.5 \
            python3.6 python3.6-distutils \
            python3.7 python3.7-distutils \
            python3.8 python3.8-distutils \
            python3.9 \
            python3.10 \
            python3.11 \
            python3.12 \
            python3.13
          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12
          pip3 install --upgrade pip setuptools wheel tox tox-gh-actions
    - name: Test with tox
      run: tox
